project:
  type: website
  output-dir: docs
  
website:
  title: "Página Web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/WalterqvPR
      - icon: github
        href: https://github.com/walterqv/website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Walter Quispe Vargas"

format:
  html:
    theme: cerulean
    toc: true

editor: source

