project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Acerca de Mi
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/WalterqvPR
      - icon: github
        href: https://github.com/walterqv
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Walter Quispe Vargas"

format:
  html:
    theme: spacelab
    toc: true

editor: source

