project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Walter Quispe Vargas
      - href: projects.qmd
        text: Proyectos
      - href: talks.qmd
        text: Presentaciones
      - href: about.qmd
        text: Acerca de Mi
      - href: pdf/WalterQuispeCV.pdf
        text: CV
    tools:
      - icon: mastodon
        href: https://mastodon.social/@walterqv
      - icon: linkedin
        href: https://www.linkedin.com/in/walter-quispe-vargas-phd-17ab871b0/
      - icon: twitter
        href: https://twitter.com/WalterqvPR
      - icon: github
        href: https://github.com/walterqv
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Walter Quispe Vargas"
  reader-mode: true
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true

editor: source

