project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Acerca de Mi
      - href: projects.qmd
        text: Proyectos
      - href: talks.qmd
        text: Presentaciones
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/walter-quispe-vargas-phd-17ab871b0/
      - icon: twitter
        href: https://twitter.com/WalterqvPR
      - icon: github
        href: https://github.com/walterqv
  page-footer:
    center: "&copy; Copyright 2023, Walter Quispe Vargas"
  reader-mode: true
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true

editor: source

